//! Init command handler
//!
//! Bootstraps the NAILS directory structure on a hidden volume.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::cli::args::InitArgs;
use nails_core::{
    RealFilesystem, ensure_hidden_hardware_configuration, stage_hidden_config_symlink,
};

/// Generated config file name used by config discovery
const CONFIG_FILE_NAME: &str = "nails.yaml";

/// Required subdirectories to create
const SUBDIRS: &[&str] = &[
    "state",
    "overlays",
    "logs",
    "config",
    "config/nixos",
    "etc",
    "etc/nixos",
    "home",
    "nix",
    ".work",
    ".work/etc",
    ".work/home",
    ".work/nix",
];

/// Build starter YAML config content with inline documentation.
fn starter_config(base: &Path) -> String {
    let hidden_path = base.display();

    format!(
        r#"# NAILS Configuration
# ===================
# This file was generated by `nails init`.
# Edit the values below to customize activation behavior.

# Hidden volume mount point.
# This should match the path you passed to `nails init`.
hidden_volume_path: "{hidden_path}"

# Whether to clear shell history on deactivation (default: true).
# clear_history: true

# Whether to run pre-flight checks before activation (default: true).
# preflight_checks: true

# Default verbosity level: quiet, info, debug
# default_verbosity: info

# Optional explicit flake reference for the hidden environment.
# nixos_flake: "{hidden_path}/nixos#your-hostname"

# Optional explicit overlay configuration.
# overlay_mode: explicit
# overlays:
#   - name: home
#     lower: /home
#     upper: "{hidden_path}/home"
#     work: "{hidden_path}/.work/home"
#     target: /home
"#
    )
}

/// Execute the init command
pub fn execute(args: InitArgs) -> Result<(), Box<dyn std::error::Error>> {
    execute_with_base_hardware_config(args, Path::new("/etc/nixos/hardware-configuration.nix"))
}

fn execute_with_base_hardware_config(
    args: InitArgs,
    base_hardware_config: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let base = &args.path;

    // Validate the path exists
    if !base.exists() {
        return Err(format!("Path does not exist: {}", base.display()).into());
    }

    if !base.is_dir() {
        return Err(format!("Path is not a directory: {}", base.display()).into());
    }

    // Create subdirectories with 0700 permissions
    for dir_name in SUBDIRS {
        let dir = base.join(dir_name);
        create_dir_0700(&dir)?;
        println!("  Created {}/", dir.display());
    }

    // Generate starter config
    let config_path = base.join("config").join(CONFIG_FILE_NAME);
    if config_path.exists() {
        println!("  Skipped {} (already exists)", config_path.display());
    } else {
        fs::write(&config_path, starter_config(base))?;
        let perms = fs::Permissions::from_mode(0o600);
        fs::set_permissions(&config_path, perms)?;
        println!("  Created {}", config_path.display());
    }

    bootstrap_hidden_nixos_layout(base, base_hardware_config)?;

    println!();
    println!(
        "NAILS directory structure initialized at {}",
        base.display()
    );

    Ok(())
}

fn bootstrap_hidden_nixos_layout(
    base: &Path,
    base_hardware_config: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let fs = RealFilesystem;

    stage_hidden_config_symlink(&fs, base)?;
    ensure_hidden_hardware_configuration(&fs, base, base_hardware_config)?;

    println!("  Ensured {}/", base.join("etc/nixos/nails").display());
    println!(
        "  Ensured {}",
        base.join("etc/nixos/hardware-configuration.nix").display()
    );
    println!(
        "  Ensured {}",
        base.join("config/nixos/configuration.nix").display()
    );

    Ok(())
}

/// Create a directory with 0700 permissions, no-op if it already exists
fn create_dir_0700(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if !path.exists() {
        fs::create_dir_all(path)?;
    }
    let perms = fs::Permissions::from_mode(0o700);
    fs::set_permissions(path, perms)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use nails_core::{
        Config, Filesystem, MockFilesystem, NailsManager, StateFile, SystemState,
        stage_hidden_config_symlink,
    };
    use std::path::Path;
    use std::sync::{Arc, Mutex};
    use tempfile::TempDir;

    fn write_test_base_hardware_config(tmp: &TempDir) -> std::path::PathBuf {
        let path = tmp
            .path()
            .join("decoy/etc/nixos/hardware-configuration.nix");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(
            &path,
            "{ config, lib, pkgs, modulesPath, ... }:\n{\n  imports = [ (modulesPath + \"/installer/scan/not-detected.nix\") ];\n}\n",
        )
        .unwrap();
        path
    }

    fn mock_init_layout(fs: &MockFilesystem, hidden_root: &Path) {
        fs.mock_set_path_exists(hidden_root.to_str().unwrap(), true);
        fs.mock_set_path_type(hidden_root.to_str().unwrap(), "directory");
        fs.mock_set_mounted(hidden_root, true);
        fs.mock_set_readable(hidden_root.to_str().unwrap(), true);
        fs.mock_set_writable(hidden_root.to_str().unwrap(), true);
        fs.mock_set_supports_symlinks(hidden_root, true);

        for rel in SUBDIRS {
            let path = hidden_root.join(rel);
            fs.mock_set_path_exists(path.to_str().unwrap(), true);
            fs.mock_set_path_type(path.to_str().unwrap(), "directory");
            fs.mock_set_readable(path.to_str().unwrap(), true);
            fs.mock_set_writable(path.to_str().unwrap(), true);
        }
    }

    fn mock_minimal_activation_prereqs(fs: &MockFilesystem) {
        fs.mock_set_path_exists("/", true);
        fs.mock_set_path_type("/", "directory");

        for dir in ["/etc", "/etc/nixos", "/home", "/nix"] {
            fs.mock_set_path_exists(dir, true);
            fs.mock_set_path_type(dir, "directory");
            fs.mock_set_readable(dir, true);
            fs.mock_set_writable(dir, true);
        }

        fs.mock_set_path_exists("/etc/nixos/hardware-configuration.nix", true);
        fs.mock_set_path_type("/etc/nixos/hardware-configuration.nix", "file");
        fs.mock_set_file_content(
            "/etc/nixos/hardware-configuration.nix",
            "{ config, lib, pkgs, ... }:\n{\n  imports = [ ];\n}\n",
        );

        fs.mock_set_path_exists("/etc/nixos/configuration.nix", true);
        fs.mock_set_path_type("/etc/nixos/configuration.nix", "file");
        fs.mock_set_file_content("/etc/nixos/configuration.nix", "{ }\n");

        fs.mock_set_root_directories(vec!["/etc".into(), "/home".into(), "/nix".into()]);
        fs.mock_set_swap_enabled(false);
    }

    #[test]
    fn test_init_creates_directory_structure() {
        let tmp = TempDir::new().unwrap();
        let base_hardware_config = write_test_base_hardware_config(&tmp);
        let args = InitArgs {
            path: tmp.path().to_path_buf(),
        };

        execute_with_base_hardware_config(args, &base_hardware_config).unwrap();

        for dir_name in SUBDIRS {
            let dir = tmp.path().join(dir_name);
            assert!(dir.is_dir(), "{} should exist", dir.display());
            let meta = fs::metadata(&dir).unwrap();
            assert_eq!(meta.permissions().mode() & 0o777, 0o700);
        }

        let config_file = tmp.path().join("config").join(CONFIG_FILE_NAME);
        assert!(config_file.is_file());
        let meta = fs::metadata(&config_file).unwrap();
        assert_eq!(meta.permissions().mode() & 0o777, 0o600);

        let contents = fs::read_to_string(&config_file).unwrap();
        assert!(contents.contains("NAILS Configuration"));
        assert!(contents.contains("# This file was generated by `nails init`."));
        assert!(contents.contains("# Hidden volume mount point."));
        assert!(contents.contains("hidden_volume_path:"));
        assert!(contents.contains("# clear_history: true"));
        assert!(contents.contains("# preflight_checks: true"));
        assert!(contents.contains("# default_verbosity: info"));
        assert!(contents.contains("# nixos_flake:"));
        assert!(contents.contains("# overlays:"));
        assert!(contents.contains(&tmp.path().display().to_string()));

        let loaded = Config::load(&config_file).unwrap();
        assert_eq!(loaded.hidden_volume_root, tmp.path());
        assert_eq!(loaded.overlay_mode, nails_core::OverlayMode::Auto);

        let hidden_config = tmp.path().join("config/nixos/configuration.nix");
        assert!(hidden_config.is_file());
        let hidden_config_meta = fs::metadata(&hidden_config).unwrap();
        assert_eq!(hidden_config_meta.permissions().mode() & 0o777, 0o600);
        let hidden_config_contents = fs::read_to_string(&hidden_config).unwrap();
        assert!(hidden_config_contents.contains("pkgs.ripgrep"));

        let hidden_hardware = tmp.path().join("etc/nixos/hardware-configuration.nix");
        assert!(hidden_hardware.is_file());
        let hidden_hardware_meta = fs::metadata(&hidden_hardware).unwrap();
        assert_eq!(hidden_hardware_meta.permissions().mode() & 0o777, 0o600);
        let hidden_hardware_contents = fs::read_to_string(&hidden_hardware).unwrap();
        assert!(hidden_hardware_contents.contains("./nails/configuration.nix"));
        assert!(
            hidden_hardware_contents.contains("modulesPath + \"/installer/scan/not-detected.nix\"")
        );

        let staged_dir = tmp.path().join("etc/nixos/nails");
        let staged_dir_meta = fs::metadata(&staged_dir).unwrap();
        assert_eq!(staged_dir_meta.permissions().mode() & 0o777, 0o700);

        let staged_symlink = tmp.path().join("etc/nixos/nails/configuration.nix");
        assert!(staged_symlink.is_symlink());
        assert_eq!(fs::read_link(&staged_symlink).unwrap(), hidden_config);
    }

    #[test]
    fn test_init_nonexistent_path() {
        let args = InitArgs {
            path: std::path::PathBuf::from("/tmp/nails-test-nonexistent-path-xyz"),
        };
        let result = execute(args);
        assert!(result.is_err());
    }

    #[test]
    fn test_init_idempotent() {
        let tmp = TempDir::new().unwrap();
        let base_hardware_config = write_test_base_hardware_config(&tmp);
        let args1 = InitArgs {
            path: tmp.path().to_path_buf(),
        };
        execute_with_base_hardware_config(args1, &base_hardware_config).unwrap();

        // Run again - should not fail
        let args2 = InitArgs {
            path: tmp.path().to_path_buf(),
        };
        execute_with_base_hardware_config(args2, &base_hardware_config).unwrap();
    }

    #[test]
    fn test_init_generated_config_is_preflight_ready_for_activation() {
        let tmp = TempDir::new().unwrap();
        let base_hardware_config = write_test_base_hardware_config(&tmp);
        execute_with_base_hardware_config(
            InitArgs {
                path: tmp.path().to_path_buf(),
            },
            &base_hardware_config,
        )
        .unwrap();

        let config_path = tmp.path().join("config").join(CONFIG_FILE_NAME);
        let config = Config::load(&config_path).unwrap();

        let fs = MockFilesystem::new();
        let hidden_root = config.hidden_volume_root.clone();

        fs.mock_set_path_exists(hidden_root.to_str().unwrap(), true);
        fs.mock_set_mounted(&hidden_root, true);
        fs.mock_set_writable(hidden_root.to_str().unwrap(), true);

        for rel in [
            "config",
            "config/nixos",
            "etc",
            "etc/nixos",
            "home",
            "nix",
            ".work",
            ".work/etc",
            ".work/home",
            ".work/nix",
        ] {
            let path = hidden_root.join(rel);
            fs.mock_set_path_exists(path.to_str().unwrap(), true);
            fs.mock_set_path_type(path.to_str().unwrap(), "directory");
            fs.mock_set_writable(path.to_str().unwrap(), true);
            fs.mock_set_readable(path.to_str().unwrap(), true);
        }

        fs.mock_set_path_exists("/etc/nixos/hardware-configuration.nix", true);
        fs.mock_set_path_type("/etc/nixos/hardware-configuration.nix", "file");
        fs.mock_set_file_content(
            "/etc/nixos/hardware-configuration.nix",
            "{ config, lib, pkgs, ... }:\n{ }",
        );
        fs.mock_set_path_exists("/etc/nixos/configuration.nix", true);
        fs.mock_set_path_type("/etc/nixos/configuration.nix", "file");
        for lower in ["/etc", "/home", "/nix"] {
            fs.mock_set_path_exists(lower, true);
            fs.mock_set_path_type(lower, "directory");
            fs.mock_set_readable(lower, true);
        }
        fs.mock_set_root_directories(vec!["/etc".into(), "/home".into(), "/nix".into()]);
        fs.mock_set_swap_enabled(false);

        stage_hidden_config_symlink(&fs, &hidden_root).unwrap();

        let manager = NailsManager::new(fs.clone(), config.clone(), config.state_file_path.clone());
        manager.run_preflight_checks(false).unwrap();

        let work_nix = hidden_root.join(".work/nix");
        assert_eq!(fs.mock_get_permissions(&work_nix), Some(0o700));

        let symlink_path = hidden_root.join("etc/nixos/nails/configuration.nix");
        assert_eq!(
            fs.mock_get_symlink_target(&symlink_path),
            Some(hidden_root.join("config/nixos/configuration.nix"))
        );
        assert!(
            fs.path_exists(&hidden_root.join("config/nixos/configuration.nix"))
                .unwrap()
        );
    }

    #[test]
    fn test_init_generated_config_activates_with_minimal_mock_filesystem_setup() {
        let tmp = TempDir::new().unwrap();
        let base_hardware_config = write_test_base_hardware_config(&tmp);
        execute_with_base_hardware_config(
            InitArgs {
                path: tmp.path().to_path_buf(),
            },
            &base_hardware_config,
        )
        .unwrap();

        let config_path = tmp.path().join("config").join(CONFIG_FILE_NAME);
        let config = Config::load(&config_path).unwrap();

        let fs = MockFilesystem::new();
        let hidden_root = config.hidden_volume_root.clone();

        mock_init_layout(&fs, &hidden_root);
        mock_minimal_activation_prereqs(&fs);

        let manager = Arc::new(Mutex::new(NailsManager::new(
            fs.clone(),
            config.clone(),
            config.state_file_path.clone(),
        )));

        NailsManager::activate(Arc::clone(&manager), false).unwrap();

        let state = manager.lock().unwrap().current_state().unwrap();
        match state {
            SystemState::Active { overlays, .. } => {
                assert_eq!(
                    overlays,
                    vec![
                        Path::new("/etc").to_path_buf(),
                        Path::new("/home").to_path_buf(),
                        Path::new("/nix").to_path_buf(),
                    ]
                );
            }
            other => panic!("expected active state after init+activate, got {other:?}"),
        }

        for target in ["/etc", "/home", "/nix"] {
            assert!(
                fs.is_mounted(Path::new(target)).unwrap(),
                "{target} should be mounted"
            );
        }

        let hidden_config = hidden_root.join("config/nixos/configuration.nix");
        assert!(fs.path_exists(&hidden_config).unwrap());
        assert!(
            !fs.read_file_content(&hidden_config)
                .unwrap()
                .trim()
                .is_empty()
        );

        let hidden_hardware = hidden_root.join("etc/nixos/hardware-configuration.nix");
        assert!(fs.path_exists(&hidden_hardware).unwrap());
        assert!(
            fs.read_file_content(&hidden_hardware)
                .unwrap()
                .contains("./nails/configuration.nix")
        );

        let staged_symlink = hidden_root.join("etc/nixos/nails/configuration.nix");
        assert_eq!(
            fs.mock_get_symlink_target(&staged_symlink),
            Some(hidden_root.join("config/nixos/configuration.nix"))
        );

        let overlayed_hardware = fs
            .get_written_content(Path::new("/etc/nixos/hardware-configuration.nix"))
            .expect("activation should inject import into overlayed hardware config");
        assert!(overlayed_hardware.contains("./nails/configuration.nix"));

        for rel in [".work/etc", ".work/home", ".work/nix"] {
            assert_eq!(fs.mock_get_permissions(&hidden_root.join(rel)), Some(0o700));
        }

        let persisted = StateFile::load(&config.state_file_path).unwrap();
        assert!(matches!(persisted.state, SystemState::Active { .. }));
        assert_eq!(persisted.overlay_status.len(), 3);
        for target in ["/etc", "/home", "/nix"] {
            assert!(
                persisted
                    .overlay_status
                    .contains_key(&Path::new(target).to_path_buf())
            );
        }
    }
}
