//! Init command handler
//!
//! Bootstraps the NAILS directory structure on a hidden volume.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::cli::args::InitArgs;
use nails_core::{
    RealFilesystem, ensure_hidden_hardware_configuration, stage_hidden_config_symlink,
};

/// Generated config file name used by config discovery
const CONFIG_FILE_NAME: &str = "nails.yaml";

/// Required subdirectories to create
const SUBDIRS: &[&str] = &[
    "overlays",
    "logs",
    "config",
    "config/nixos",
    "etc",
    "etc/nixos",
    "home",
    "nix",
    ".work",
    ".work/etc",
    ".work/home",
    ".work/nix",
];

/// Build starter YAML config content with inline documentation.
fn starter_config(base: &Path) -> String {
    let hidden_path = base.display();

    format!(
        r#"# NAILS Configuration
# ===================
# This file was generated by `nails init`.
# Edit the values below to customize activation behavior.

# Hidden volume mount point.
# This should match the path you passed to `nails init`.
hidden_volume_path: "{hidden_path}"

# Whether to clear shell history on deactivation (default: true).
# clear_history: true

# Whether to run pre-flight checks before activation (default: true).
# preflight_checks: true

# Default verbosity level: quiet, info, debug
# default_verbosity: info

# Optional explicit flake reference for the hidden environment.
# nixos_flake: "{hidden_path}/nixos#your-hostname"

# Optional explicit overlay configuration.
# overlay_mode: explicit
# overlays:
#   - name: home
#     lower: /home
#     upper: "{hidden_path}/home"
#     work: "{hidden_path}/.work/home"
#     target: /home
"#
    )
}

/// Execute the init command
pub fn execute(args: InitArgs) -> Result<(), Box<dyn std::error::Error>> {
    execute_with_base_hardware_config(args, Path::new("/etc/nixos/hardware-configuration.nix"))
}

fn execute_with_base_hardware_config(
    args: InitArgs,
    base_hardware_config: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let base = &args.path;

    // Validate the path exists
    if !base.exists() {
        return Err(format!("Path does not exist: {}", base.display()).into());
    }

    if !base.is_dir() {
        return Err(format!("Path is not a directory: {}", base.display()).into());
    }

    // Create subdirectories with 0700 permissions
    for dir_name in SUBDIRS {
        let dir = base.join(dir_name);
        create_dir_0700(&dir)?;
        println!("  Created {}/", dir.display());
    }

    // Generate starter config
    let config_path = base.join("config").join(CONFIG_FILE_NAME);
    if config_path.exists() {
        println!("  Skipped {} (already exists)", config_path.display());
    } else {
        fs::write(&config_path, starter_config(base))?;
        let perms = fs::Permissions::from_mode(0o600);
        fs::set_permissions(&config_path, perms)?;
        println!("  Created {}", config_path.display());
    }

    create_initial_state_file(base)?;

    bootstrap_hidden_nixos_layout(base, base_hardware_config)?;

    println!();
    println!(
        "NAILS directory structure initialized at {}",
        base.display()
    );

    Ok(())
}

fn bootstrap_hidden_nixos_layout(
    base: &Path,
    base_hardware_config: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let fs = RealFilesystem;

    stage_hidden_config_symlink(&fs, base)?;
    ensure_hidden_hardware_configuration(&fs, base, base_hardware_config)?;

    println!("  Ensured {}/", base.join("etc/nixos/nails").display());
    println!(
        "  Ensured {}",
        base.join("etc/nixos/hardware-configuration.nix").display()
    );
    println!(
        "  Ensured {}",
        base.join("config/nixos/configuration.nix").display()
    );

    Ok(())
}

/// Create a directory with 0700 permissions, no-op if it already exists
fn create_dir_0700(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if !path.exists() {
        fs::create_dir_all(path)?;
    }
    let perms = fs::Permissions::from_mode(0o700);
    fs::set_permissions(path, perms)?;
    Ok(())
}

fn create_initial_state_file(base: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let state_path = base.join("state.json");

    if state_path.exists() {
        if !state_path.is_file() {
            return Err(format!(
                "State path exists but is not a file: {}",
                state_path.display()
            )
            .into());
        }
        println!("  Skipped {} (already exists)", state_path.display());
        return Ok(());
    }

    nails_core::StateFile::default().save_with_custom_root(&state_path, base)?;
    println!("  Created {}", state_path.display());

    Ok(())
}

#[cfg(test)]
mod tests;
