# Test 45: Init Bootstrap

{ self, ... }:
let
  hiddenVolume = import ./../../lib/hidden-volume.nix;
in
{
  name = "init-bootstrap";
  meta.tags = [
    "init"
    "smoke"
  ];

  nodes.machine =
    { ... }:
    {
      imports = [ ./../../lib/vm-config.nix ];
      environment.systemPackages = [ self.packages.x86_64-linux.nails ];
    };

  testScript = _: ''
    machine.start()
    machine.wait_for_unit("multi-user.target")

    expected_dirs = [
        "/mnt/hidden-volume/state",
        "/mnt/hidden-volume/overlays",
        "/mnt/hidden-volume/logs",
        "/mnt/hidden-volume/config",
        "/mnt/hidden-volume/config/nixos",
        "/mnt/hidden-volume/etc",
        "/mnt/hidden-volume/etc/nixos",
        "/mnt/hidden-volume/etc/nixos/nails",
        "/mnt/hidden-volume/home",
        "/mnt/hidden-volume/nix",
        "/mnt/hidden-volume/.work",
        "/mnt/hidden-volume/.work/etc",
        "/mnt/hidden-volume/.work/home",
        "/mnt/hidden-volume/.work/nix",
    ]

    expected_files = {
        "/mnt/hidden-volume/config/nails.yaml": "600",
        "/mnt/hidden-volume/config/nixos/configuration.nix": "600",
        "/mnt/hidden-volume/etc/nixos/hardware-configuration.nix": "600",
    }

    with subtest("prepare bare hidden volume"):
        machine.succeed("""${hiddenVolume.setupHiddenVolume}""")
        machine.succeed("bash -lc 'shopt -s dotglob nullglob && rm -rf /mnt/hidden-volume/*'")
        machine.succeed("test -z \"$(ls -A /mnt/hidden-volume)\"")
    with subtest("run init bootstrap"):
        machine.succeed("nails init /mnt/hidden-volume")

    with subtest("assert directory skeleton and permissions"):
        for path in expected_dirs:
            machine.succeed(f"test -d {path}")
            perms = machine.succeed(f"stat -c %a {path}").strip()
            assert perms == "700", f"Expected 0700 on {path}, got {perms}"

    with subtest("assert generated files and symlink staging"):
        for path, expected_perm in expected_files.items():
            machine.succeed(f"test -f {path}")
            perms = machine.succeed(f"stat -c %a {path}").strip()
            assert perms == expected_perm, f"Expected {expected_perm} on {path}, got {perms}"

        machine.succeed("test -L /mnt/hidden-volume/etc/nixos/nails/configuration.nix")
        target = machine.succeed("readlink /mnt/hidden-volume/etc/nixos/nails/configuration.nix").strip()
        assert target == "/mnt/hidden-volume/config/nixos/configuration.nix", target

    with subtest("assert generated config content"):
        config_text = machine.succeed("cat /mnt/hidden-volume/config/nails.yaml")
        assert "# This file was generated by `nails init`." in config_text, config_text
        assert 'hidden_volume_path: "/mnt/hidden-volume"' in config_text, config_text

        hardware_text = machine.succeed("cat /mnt/hidden-volume/etc/nixos/hardware-configuration.nix")
        assert "./nails/configuration.nix" in hardware_text, hardware_text

        hidden_config = machine.succeed("cat /mnt/hidden-volume/config/nixos/configuration.nix")
        assert "pkgs.ripgrep" in hidden_config, hidden_config
  '';
}
